### ISSUE TITLE
Lua files and usually excluded folders

### ISSUE THREAD

**Issue by Xibitol** [brennondenny/vsc-jetbrains-icons-enhanced#1]
**Hey !**

I'm just installed your icons theme for vscode and this is a really good job, thanks.

Although, I've a request for a two new icon :
- Lua files
- And excluded folders in idea (That are orange). Usually this is the `out` folder and all its childs (If this is possible)

**Thanks in advance.**

**Comment by brennondenny** [comment]
I'll add an icon for .lua file extensions, but can you provide more info on your second bullet point? Right now the only folders that are given the orange folder icon are "scripts" folders.

**Comment by brennondenny** [comment]
Added support for Lua files
