### ISSUE TITLE
What about Liquid? :^)

### ISSUE THREAD

**Issue by ed-ponce** [brennondenny/vsc-jetbrains-icons-enhanced#10]

**Comment by brennondenny** [comment]
I'm not familiar, can you link or clarify?

**Comment by ed-ponce** [comment]
Liquid is the templating language for Shopify themes. Jekyll and Eleventy also implemented it.

* https://liquidjs.com
* https://shopify.dev/docs/api/liquid

Other icon themes represent it with a droplets, waves or Shopify’s bag isologo.

**Comment by brennondenny** [comment]
![CleanShot 2024-09-27 at 17 29 23](https://github.com/user-attachments/assets/e79262c9-d839-44f8-bba5-47406b4cd156)

Thoughts?

**Comment by ed-ponce** [comment]
Exactly!

**Comment by brennondenny** [comment]
Released update
