### ISSUE TITLE
Request to add header file icon support

### ISSUE THREAD

**Issue by Logix-Dev** [brennondenny/vsc-jetbrains-icons-enhanced#3]
Hi. I would like to request that you please add the icons for .h and .hpp files.
This helps greatly in discerning headers from source files at a glance.

Current:
![image](https://user-images.githubusercontent.com/72663050/220143356-a3ed602d-e6dd-4eb5-99e6-fdce02d4fb4d.png)

Expected:
![image](https://user-images.githubusercontent.com/72663050/220143290-0417bfd4-c972-4869-b7b7-719e3f7053ab.png)

Thanks!

**Comment by brennondenny** [comment]
updated 👍

**Comment by Logix-Dev** [comment]
Perfect, thank you very much!
